### ISSUE TITLE
How to read velX_R.dat

### ISSUE THREAD

**Issue by jiangyuinsar** [sozawa94/hbi#1]
Hello So,

Many thanks for your great work and sharing the codes! I have a question about loading HBI output file, **velX_R.dat**.

As you mentioned in the user guide, '_The field data are saved in binary stream files. xyzX_R.dat is the coordinates of the elements. velX_R.dat. tauX_R.dat. sigmaX_R.dat, and slipX_R.dat are slip velocity, shear stress, normal stress, and slip every interval time steps, respectively. These are binary stream files._' 

I try to read **velX_R.dat** in **Matlab**, but the data format and numeric type are unknown. Could you provide me with some clues?

Thanks for your time and help.

Kind regards,
Yu

**Comment by sozawa94** [comment]
Hello Yu,

Thanks for your interest in our codes!
I have added plotvel.m, which is a simple Matlab script that plots a slip velocity distribution.
Please note that plotvel.m is for a single processor.

Best Regards,
So

**Comment by jiangyuinsar** [comment]
Hi So,

This works for me! Thanks for your help.

Cheers,
Yu
